name: routgen_generator
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  source_gen: ^0.9.5
  build: ^1.2.2
  path: ^1.6.4

dev_dependencies:
  build_runner: ^1.8.0

assets: