name: routgen_generator
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  source_gen: ^1.0.0
  build: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^1.8.0
